### ISSUE TITLE
Support more recent devpi-server version (which uses sha256 instead of md5)

### ISSUE THREAD

**Issue by k-bu** [devpi/devpi-findlinks#3]
Hi,

we're using devpi-server-2.2.2:
  File ".../lib/python2.7/site-packages/devpi_findlinks/main.py", line 50, in findlinks_view
    elif entry.md5:
AttributeError: unreadable attribute

I bluntly changed that line(s) of code to:
    elif hasattr(entry, "sha256") and entry.sha256:

Well, the exception is gone, but there still aren't any checksums in the generated hyperlinks :\

Regards

**Comment by fschulze** [comment]
https://pypi.python.org/pypi/devpi-findlinks/1.0.1
