### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by LordGaav** [devpi/devpi-findlinks#9]
Does this plugin work with devpi-server 6.3.1? All routes seem to return redirects, which end up in 404 errors for me:

http://host/pip/live/+findlinks - 302 to:
http://host/pip/live/-findlinks - 404

I'm using these versions and plugins:

    devpi-findlinks-2.0.1
    devpi-lockdown-2.0.0
    devpi-server-6.3.1
    devpi-slack-0.1.3
    devpi-web-4.0.8

**Comment by fschulze** [comment]
I'll have to take a look, something might have broken it. What is your use-case for the plugin? I personally haven't required it for quite some time.

**Comment by LordGaav** [comment]
Me neither, I'm not even quite sure what the plugin does :sweat_smile:  . I seem to have added it to my Docker image a long time ago. When I did an upgrade today I checked all the plugins to see if they still worked, and this one seems broken.

**Comment by stevedrees** [comment]
I have some legacy products that use find-links to load from a cheeseshop we are migrating to devpi. It would be nice if this worked with devpi-server => 6.5.0

devpi-findlinks-2.0.1
devpi-server-6.5.0
devpi-web-4.0.8

**Comment by fschulze** [comment]
The problem was that the plugin didn't register when using pluggy >= 1.0.0.
I released devpi-findlinks 3.0.0 to fix that.
